import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Affiliate from '../components/home/Affiliate.jsx'
import AppInfo from '../components/home/AppInfo.jsx'
import CoinOneCore from '../components/home/CoinOneCore.jsx'
import Main from '../components/home/Main.jsx'
import Service from '../components/home/Service.jsx'
import Slick from '../components/home/Slick.jsx'
import Top from '../components/home/Top.jsx'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Slick/>
        <Top/>
        <Main/>
        <AppInfo/>
        <Service/>
        <CoinOneCore/>
        <Affiliate/>
      </div>
    </div>
  )
}
